version: '3'
services:
  spark-csv-harvest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./spark_history_logs:/tmp/spark-events

  spark-history-server:
    image: "rangareddy1988/spark-history-server:latest"
    environment:
      SPARK_HISTORY_UI_PORT: "18080"
      SPARK_DAEMON_MEMORY: "4g"
      SPARK_HISTORY_RETAINEDAPPLICATIONS: "200"
      SPARK_HISTORY_UI_MAXAPPLICATIONS: "500"
    ports:
      - "18080:18080"
    volumes:
      - ./spark_history_logs:/tmp/spark-events
